---
- name: Building Handson Host
  hosts: "{{ target }}"
  gather_facts: no

  roles:
    - { role: openstack-office, when: "vtype == 'OpenStack' and target == 'ops'" }
    - { role: openstack-home, when: "vtype == 'OpenStack' and target == 'ops-home'"}
    - { role: dc, when: "vtype == 'DC'" }
    - { role: aws, when: "vtype == 'AWS'" }
    #- { role: azure, when: "vtype == 'Azure'" }

    # For Bare Metal or VM
    - { role: common, set_resolv: true , when: "vtype == 'Bare'"}
    - { role: ansible, when: "vtype == 'Bare'" }
    - { role: docker, when: "vtype == 'Bare'" }
    - { role: handson, when: "vtype == 'Bare'" }

- name: OpenStack in Office
  hosts: launched-office
  gather_facts: no
  become: true
  become_user: root
  roles:
    - common
    - ansible
    - docker
    - handson
  environment: "{{ proxy_env }}"

- name: OpenStack in Home
  hosts: launched-home
  gather_facts: yes
  become: true
  become_user: root
  roles:
    - { role: common, when: "lesson is defined" , set_resolv: true }
    - ansible
    - { role: docker ,  when: "lesson is defined" }
    - { role: handson ,  when: "lesson is defined" }
    #- zeppelin

- name: On AWS
  hosts: launched-aws
  gather_facts: no
  become: true
  become_user: root
  roles:
    - common
    - ansible
    - docker
    - handson

- name: On DigitalOcean
  hosts: launched-dc
  gather_facts: yes

  roles:
    - common
    - ansible
    - docker
    - handson
    #- zeppelin
