---
- hosts: "{{ target }}"
  gather_facts: no

  roles:
    - { role: openstack-office, when: "vtype == 'OpenStack' and target == 'ops'" }
    - { role: openstack-home, when: "vtype == 'OpenStack'" }
    - { role: dc, when: "vtype == 'DC'" }
    #- { role: aws, when: "vtype == 'AWS'" }
    #- { role: azure, when: "vtype == 'Azure'" }

    # For Bare Metal or VM
    - { role: common, set_resolv: true , when: "vtype == 'Bare'"}
    - { role: ansible, when: "vtype == 'Bare'" }
    - { role: docker, when: "vtype == 'Bare'" }
    - { role: handson, when: "vtype == 'Bare'" }

# OpenStack in Office
- hosts: launched-office
  gather_facts: no
  become: true
  become_user: root
  roles:
    - common
    - ansible
    - docker
    - handson
  environment: "{{ proxy_env }}"

# OpenStack in Home or AWS
- hosts: launched-home
  gather_facts: no
  become: true
  become_user: root
  roles:
    - { role: common, set_resolv: true }
    - ansible
    - docker
    - handson

# DigitalOcean
- hosts: c_launched
  gather_facts: no

  roles:
    - common
    - ansible
    - docker
    - handson
